### ISSUE TITLE
API is out of date

### ISSUE THREAD

**Issue by tesselode** [rameshvarun/autocomplete-love#1]
Or at the very least, some of the love.physics functions are out of date. For example, newRectangleShape is still the one from pre-0.8.0.

**Comment by rameshvarun** [comment]
I'm finally getting around to this since school is winding down. Right now, all the API definitions are generated from [rm-code/api](https://github.com/rm-code/love-api), so I've made a pull request - https://github.com/rm-code/love-api/pull/11

I think its worth looking into auto-generating definitions directly from the Wiki - it seems structured enough.

**Comment by rameshvarun** [comment]
This was fixed in 1aebbcbc4a997a50589da91f8ecb3b039fb5f395, but I forgot to close this issue.
